version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "bubaley"
    assignees:
      - "bubaley"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic*"
        update-types: ["version-update:semver-major"]
    groups:
      fastapi-ecosystem:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "starlette*"
      development-tools:
        patterns:
          - "ruff*"
          - "pre-commit*"
          - "pytest*"
          - "coverage*"
      security-tools:
        patterns:
          - "bandit*"
          - "safety*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "bubaley"
    assignees:
      - "bubaley"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      docker-actions:
        patterns:
          - "docker/*"
      security-actions:
        patterns:
          - "aquasecurity/*"
          - "anchore/*"
          - "github/codeql-action"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "bubaley"
    assignees:
      - "bubaley"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker" 