name: backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    name: Backend setup
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: example-secret-key

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install packages
        run: uv sync
      - name: Lint
        run: uv run make lint
