name: Publish Docker Image

on:
  workflow_run:
    workflows: ["backend"]
    types:
      - completed
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        run: |
          docker build . -t $DOCKER_IMAGE_NAME:latest
          docker build . -t $DOCKER_IMAGE_NAME:$VERSION
          docker push $DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_IMAGE_NAME:$VERSION
